apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    tier: database
data:
  POSTGRES_DB: classproject
  POSTGRES_USER: projectuser
  POSTGRES_PASSWORD: projectpassword
  POSTGRES_PORT: "30010"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
    tier: database
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim           
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-service
#   labels:
#     app: postgres
#     tier: database
# spec:
#   type: NodePort
#   ports:
#    - port: 5432
#      nodePort: 30010
#      name: postgres
#   selector:
#    app: postgres
#    tier: database

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    #app: postgres
    #tier: database
    service: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432  
     name: postgres   
  selector:
    service: postgres